apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
  labels:
   app: myapp
spec:
  replicas: 1
  selector:
   matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: appimage
        name: myapplication
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
