apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
  labels:
   app: myapp
spec:
  replicas: 1
  selector:
   matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: appimage
        name: myapplication
        ports:
        - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: myfrontend
  labels:
    app: myapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: myapp
