apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
  labels:
   app: myapp
spec:
  replicas: 1
  selector:
   matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: appimage
        name: myapplication
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myfrontend
  labels:
    app: myapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: myfrontend
  labels:
    app: myapp

spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80

  selector:
    app: myapp
  type: LoadBalancer
status:
  loadBalancer: {} 
