version: '3.1'

services:

  db:
    image: mysql
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./db/:/docker-entrypoint-initdb.d
    
    env_file:
     - sql.env
     
    #environment:
      
    expose:
    - "3306"
    
  app:
    image: appimage
    container_name: myapplication
    ports:
    - "80:80"
    depends_on:
    - "db"
